#!/usr/bin/env bash
# Installs and configures Nginx on web01 server to serve a Hello World! page

echo -e "uodating and installing Nginx.\n"
sudo apt-get update -y -qq &&\
apt-get install -y nginx
	sudo apt-get install nginx -y

echo -e "\nsetting up some minor stuff.\n"

# strart nginx service
sudo service nginx start

#allowing nginx on firewell
sudo ufw allow "nginx HTTP"

# Give to user ownership to website files for easy editing
sudo chown -R "$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backup default index 
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Restarting nginx
sudo service nginx restart

echo -e "\nComleted."
