#!/usr/bin/env bash

#display the  content of the file /etc/passswd

while IFS=: read -r username _ uid _ _ homedir _; do
	echo "username: $passwd", UID: $uid, Home Directory: $homedir"
done < "/etc/passwd"
