#!/usr/bin/env bash
#Display the number from one to twenty, in addition to:
# "bad luck from china for 4th iteration
#"bad luck from japan" for 9th iteration
#"bad luck from italy for 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( counter++ ))
done
